# Support the author by using the funding links below.
# GitHub Sponsors: https://github.com/sponsors/mkazin
# Buy Me a Coffee: https://buymeacoffee.com/mkazin

github: mkazin
buy_me_a_coffee: mkazin
